---
- name: Update Proxmox VE repositories
  ansible.builtin.include_tasks:
    file: repos.yml

- name: Remove subscription nag
  ansible.builtin.include_tasks:
    file: nag.yml
  when: proxmox_remove_subscription_nag

- name: Disable HA services
  ansible.builtin.include_tasks:
    file: ha.yml
  when: proxmox_disable_ha_services
