---
- name: Deploy subscription nag removal script
  ansible.builtin.copy:
    src: pve-remove-nag.sh
    dest: /usr/local/bin/pve-remove-nag.sh
    owner: root
    group: root
    mode: '0755'
  notify: run_nag_removal

- name: Deploy subscription nag APT hook
  ansible.builtin.copy:
    content: |
      DPkg::Post-Invoke { "/usr/local/bin/pve-remove-nag.sh"; };
    dest: /etc/apt/apt.conf.d/no-nag-script
    owner: root
    group: root
    mode: '0644'
