---
dependency:
  enabled: false
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: "/bin/bash -c 'sleep infinity'"
provisioner:
  name: ansible
verifier:
  name: ansible
